In [1]:
import pandas as pd
from load import Load
from submission import Submission
from tournament import Tournament
import time
# from Simulation

In [2]:
mw = 'W'
ncaa_files = Load(mw)
df = pd.read_csv('./input/'+mw+'Submission.csv')
submission = Submission(sub_df=df, files=ncaa_files)

In [3]:
game_id = submission.predictions.loc[0].game_id
pred = submission.get_pred(game_id)
pred

93.4% chance of Arizona beating SUNY Albany

In [5]:
tourney = Tournament(ncaa_files,submission,2019)
tourney.simulate_tournament('chalk',seed=13)

Simulating round 0...
2019 - W11: Belmont vs. Temple
Temple wins!

2019 - W16: N Dakota St vs. NC Central
N Dakota St wins!

2019 - X11: Arizona St vs. St John's
St John's wins!

2019 - X16: F Dickinson vs. Prairie View
F Dickinson wins!

Simulating round 1...
2019 - R1W1: Duke vs. N Dakota St
Duke wins!

2019 - R1W2: Michigan St vs. Bradley
Michigan St wins!

2019 - R1W3: LSU vs. Yale
LSU wins!

2019 - R1W4: Virginia Tech vs. St Louis
Virginia Tech wins!

2019 - R1W5: Mississippi St vs. Liberty
Mississippi St wins!

2019 - R1W6: Maryland vs. Temple
Maryland wins!

2019 - R1W7: Louisville vs. Minnesota
Louisville wins!

2019 - R1W8: VCU vs. UCF
UCF wins!

2019 - R1X1: Gonzaga vs. F Dickinson
Gonzaga wins!

2019 - R1X2: Michigan vs. Montana
Michigan wins!

2019 - R1X3: Texas Tech vs. N Kentucky
Texas Tech wins!

2019 - R1X4: Florida St vs. Vermont
Florida St wins!

2019 - R1X5: Marquette vs. Murray St
Marquette wins!

2019 - R1X6: Buffalo vs. St John's
Buffalo wins!

2019 - R1X7: Nevada vs. Florida
Nevada wins!

2019 - R1X8: Syracuse vs. Baylor
Syracuse wins!

2019 - R1Y1: North Carolina vs. Iona
North Carolina wins!

2019 - R1Y2: Kentucky vs. Abilene Chr
Kentucky wins!

2019 - R1Y3: Houston vs. Georgia St
Houston wins!

2019 - R1Y4: Kansas vs. Northeastern
Kansas wins!

2019 - R1Y5: Auburn vs. New Mexico St
Auburn wins!

2019 - R1Y6: Iowa St vs. Ohio St
Iowa St wins!

2019 - R1Y7: Wofford vs. Seton Hall
Wofford wins!

2019 - R1Y8: Utah St vs. Washington
Washington wins!

2019 - R1Z1: Virginia vs. Gardner Webb
Virginia wins!

2019 - R1Z2: Tennessee vs. Colgate
Tennessee wins!

2019 - R1Z3: Purdue vs. Old Dominion
Purdue wins!

2019 - R1Z4: Kansas St vs. UC Irvine
Kansas St wins!

2019 - R1Z5: Wisconsin vs. Oregon
Wisconsin wins!

2019 - R1Z6: Villanova vs. St Mary's CA
Villanova wins!

2019 - R1Z7: Cincinnati vs. Iowa
Cincinnati wins!

2019 - R1Z8: Mississippi vs. Oklahoma
Mississippi wins!

Simulating round 2...
2019 - R2W1: Duke vs. UCF
Duke wins!

2019 - R2W2: Michigan St vs. Louisville
Michigan St wins!

2019 - R2W3: LSU vs. Maryland
LSU wins!

2019 - R2W4: Virginia Tech vs. Mississippi St
Virginia Tech wins!

2019 - R2X1: Gonzaga vs. Syracuse
Gonzaga wins!

2019 - R2X2: Michigan vs. Nevada
Michigan wins!

2019 - R2X3: Texas Tech vs. Buffalo
Texas Tech wins!

2019 - R2X4: Florida St vs. Marquette
Florida St wins!

2019 - R2Y1: North Carolina vs. Washington
North Carolina wins!

2019 - R2Y2: Kentucky vs. Wofford
Kentucky wins!

2019 - R2Y3: Houston vs. Iowa St
Houston wins!

2019 - R2Y4: Kansas vs. Auburn
Kansas wins!

2019 - R2Z1: Virginia vs. Mississippi
Virginia wins!

2019 - R2Z2: Tennessee vs. Cincinnati
Tennessee wins!

2019 - R2Z3: Purdue vs. Villanova
Villanova wins!

2019 - R2Z4: Kansas St vs. Wisconsin
Kansas St wins!

Simulating round 3...
2019 - R3W1: Duke vs. Virginia Tech
Duke wins!

2019 - R3W2: Michigan St vs. LSU
Michigan St wins!

2019 - R3X1: Gonzaga vs. Florida St
Gonzaga wins!

2019 - R3X2: Michigan vs. Texas Tech
Michigan wins!

2019 - R3Y1: North Carolina vs. Kansas
North Carolina wins!

2019 - R3Y2: Kentucky vs. Houston
Houston wins!

2019 - R3Z1: Virginia vs. Kansas St
Virginia wins!

2019 - R3Z2: Tennessee vs. Villanova
Tennessee wins!

Simulating round 4...
2019 - R4W1: Duke vs. Michigan St
Duke wins!

2019 - R4X1: Gonzaga vs. Michigan
Gonzaga wins!

2019 - R4Y1: North Carolina vs. Houston
Houston wins!

2019 - R4Z1: Virginia vs. Tennessee
Virginia wins!

Simulating round 5...
2019 - R5WX: Duke vs. Gonzaga
Duke wins!

2019 - R5YZ: Houston vs. Virginia
Virginia wins!

Simulating round 6...
2019 - R6CH: Duke vs. Virginia
Duke wins!

Done

In [10]:
# start = time.time()
# for _ in range(1000):
#     tourney = Tournament(files,submission,2018)
#     tourney.simulate_tournament('random',seed=14)
# end = time.time()
# print(end-start)

In [8]:
tourney.simulate_round('random',seed=0)

{'W11': <tournament.Team object at 0x1362de940>, 'W16': <tournament.Team object at 0x1362dea90>, 'X11': <tournament.Team object at 0x1362deb80>, 'Z16': <tournament.Team object at 0x1362dec70>}

In [9]:
tourney.games.head(20)

2117          2018 - R1W1: Villanova vs. Radford
2118        2018 - R1W2: Purdue vs. CS Fullerton
2119       2018 - R1W3: Texas Tech vs. SF Austin
2120        2018 - R1W4: Wichita St vs. Marshall
2121    2018 - R1W5: West Virginia vs. Murray St
2122     2018 - R1W6: Florida vs. St Bonaventure
2123            2018 - R1W7: Arkansas vs. Butler
2124      2018 - R1W8: Virginia Tech vs. Alabama
2125                2018 - R1X1: Kansas vs. Penn
2126                  2018 - R1X2: Duke vs. Iona
2127       2018 - R1X3: Michigan St vs. Bucknell
2128      2018 - R1X4: Auburn vs. Col Charleston
2129      2018 - R1X5: Clemson vs. New Mexico St
2130               2018 - R1X6: TCU vs. Syracuse
2131      2018 - R1X7: Rhode Island vs. Oklahoma
2132        2018 - R1X8: Seton Hall vs. NC State
2133              2018 - R1Y1: Virginia vs. UMBC
2134      2018 - R1Y2: Cincinnati vs. Georgia St
2135        2018 - R1Y3: Tennessee vs. Wright St
2136            2018 - R1Y4: Arizona vs. Buffalo
dtype: object

In [5]:
tourney.games.apply(lambda x: x.get_winner(submission,'random') if not x.team_is_missing() else None)

2117       NaN
2118    1345.0
2119    1403.0
2120    1455.0
2121    1452.0
         ...
2179       NaN
2180    1382.0
2181    1347.0
2182    1393.0
2183    1411.0
Length: 67, dtype: float64

In [6]:
tourney.games.apply(lambda x: x.r)

2117    1
2118    1
2119    1
2120    1
2121    1
       ..
2179    6
2180    0
2181    0
2182    0
2183    0
Length: 67, dtype: int64

IndexError: list index out of range

In [8]:
preds = submission.get_pred()
preds

0         93.4% chance of Arizona beating SUNY Albany
1        85.9% chance of Arkansas beating SUNY Albany
2          85.7% chance of Baylor beating SUNY Albany
3         64.1% chance of Belmont beating SUNY Albany
4        80.9% chance of Boise St beating SUNY Albany
                             ...
11385      58.4% chance of Washington beating Wofford
11386         73.6% chance of Washington beating Yale
11387       63.8% chance of Wisconsin beating Wofford
11388          79.0% chance of Wisconsin beating Yale
11389            66.3% chance of Wofford beating Yale
Length: 11390, dtype: object

In [7]:
game_id = preds[0].game_id

alt_game_id = game_id.split('_')
alt_game_id = '_'.join([alt_game_id[0],
          alt_game_id[2],
          alt_game_id[1]
          ])

pred = submission.get_pred(alt_game_id)
# pred
# # for _, row in submission.df.iterrows():
# #     print(type(row))

In [8]:
pred.get_loss(team=pred.t2_id)

0.06796646334691586

In [7]:
pred.get_random()

1112

In [8]:
# files = Files(mw='W')
# files.seasons

In [14]:
games, desc_txt = tourney.simulation('chalk')
games

      Slot  StrongSeed     WeakSeed Round Game StrongID WeakID  WinID GameID
2050  R1W1     East-01     East-16a    R1   W1     1437    W16      0    NaN
2051  R1W2     East-02      East-15    R1   W2     1181   1407      0    NaN
2052  R1W3     East-03      East-14    R1   W3     1124   1308      0    NaN
2053  R1W4     East-04      East-13    R1   W4     1196   1190      0    NaN
2054  R1W5     East-05      East-12    R1   W5     1438   1423      0    NaN
2055  R1W6     East-06     East-11a    R1   W6     1374    W11      0    NaN
2056  R1W7     East-07      East-10    R1   W7     1376   1266      0    NaN
2057  R1W8     East-08      East-09    R1   W8     1458   1439      0    NaN
2058  R1X1     West-01      West-16    R1   X1     1211   1355      0    NaN
2059  R1X2     West-02      West-15    R1   X2     1112   1315      0    NaN
2060  R1X3     West-03      West-14    R1   X3     1199   1195      0    NaN
2061  R1X4     West-04      West-13    R1   X4     1452   1137      0    NaN
2062  R1X5     West-05      West-12    R1   X5     1323   1343      0    NaN
2063  R1X6     West-06      West-11    R1   X6     1268   1462      0    NaN
2064  R1X7     West-07      West-10    R1   X7     1388   1433      0    NaN
2065  R1X8     West-08      West-09    R1   X8     1321   1435      0    NaN
2066  R1Y1  Midwest-01  Midwest-16b    R1   Y1     1242    Y16      0    NaN
2067  R1Y2  Midwest-02   Midwest-15    R1   Y2     1257   1240      0    NaN
2068  R1Y3  Midwest-03   Midwest-14    R1   Y3     1332   1233      0    NaN
2069  R1Y4  Midwest-04   Midwest-13    R1   Y4     1345   1436      0    NaN
2070  R1Y5  Midwest-05   Midwest-12    R1   Y5     1235   1305      0    NaN
2071  R1Y6  Midwest-06   Midwest-11    R1   Y6     1166   1348      0    NaN
2072  R1Y7  Midwest-07   Midwest-10    R1   Y7     1276   1329      0    NaN
2073  R1Y8  Midwest-08   Midwest-09    R1   Y8     1274   1277      0    NaN
2074  R1Z1    South-01     South-16    R1   Z1     1314   1411      0    NaN
2075  R1Z2    South-02     South-15    R1   Z2     1246   1297      0    NaN
2076  R1Z3    South-03     South-14    R1   Z3     1417   1245      0    NaN
2077  R1Z4    South-04     South-13    R1   Z4     1139   1457      0    NaN
2078  R1Z5    South-05     South-12    R1   Z5     1278   1292      0    NaN
2079  R1Z6    South-06    South-11a    R1   Z6     1153    Z11      0    NaN
2080  R1Z7    South-07     South-10    R1   Z7     1173   1455      0    NaN
2081  R1Z8    South-08     South-09    R1   Z8     1116   1371      0    NaN

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [11]:
None

In [15]:
tourney.slots

,Slot,StrongSeed,WeakSeed,Round,Game,StrongID,WeakID,WinID,GameID
2050,R1W1,East-01,East-16a,R1,W1,1437,W16,0,NaN
2051,R1W2,East-02,East-15,R1,W2,1181,1407,0,NaN
2052,R1W3,East-03,East-14,R1,W3,1124,1308,0,NaN
2053,R1W4,East-04,East-13,R1,W4,1196,1190,0,NaN
2054,R1W5,East-05,East-12,R1,W5,1438,1423,0,NaN
...,...,...,...,...,...,...,...,...,...
2112,R6CH,R5WX,R5YZ,R6,CH,R5WX,R5YZ,0,NaN
2113,W11,East-11a,East-11b,R0,W11,1344,1425,1344,2017_1344_1425
2114,W16,East-16a,East-16b,R0,W16,1291,1309,1291,2017_1291_1309
2115,Y16,Midwest-16a,Midwest-16b,R0,Y16,1300,1413,1413,2017_1300_1413
2116,Z11,South-11a,South-11b,R0,Z11,1243,1448,1243,2017_1243_1448

In [13]:
tourney.next_round_dict

{'W11': 'East-11a',
 'W16': 'East-16a',
 'Y16': 'Midwest-16b',
 'Z11': 'South-11a'}